### ISSUE TITLE
Feature request: podpora zobrazování známek

### ISSUE THREAD

**Issue by paper42** [vitSkalicky/lepsi-rozvrh#2]
Rád bych se zbavil oficiální aplikace úplně, ale zatím mi v tom brání absence přehledu známek. Je to v plánu? Oficiální aplikace se někdy rozhodne nezobrazit notifikaci o nové známce a na některých telefonech to nefunguje vůbec.

Děkuji za úžasnou práci.

**Comment by vitSkalicky** [comment]
Kdybych chtěl přidat zobrzování známek, musel bych aplikaci hodně předělat, protože od začátku byla stavěná pouze na rozvrh. Každopádně i s rozvrhem bude ještě hodně práce, takže i kdybych chtěl, tak by se podpora známek neoběvila dřív než za několik měsíců. Možná se někdy v budoucnu vrhnu na vytvoření celého klienta nebo se o to můžeš pokusit sám. Lepší rozvrh je svobodný software, takže jeho kód můžeš použít ve svojí aplikaci, pokud bude zveřejněna taky pod GPLv3.

TLDR; já to v plánu nemám, můžeš udělat fork.
