### ISSUE TITLE
Donate link

### ISSUE THREAD

**Issue by Tassil0** [vitSkalicky/lepsi-rozvrh#6]
Hoši kam vám můžu poslat donate, chci vás podpořit. Odvedli jste skvělou práci, tahle appka je úžasná. Bakalář by vás měl najmout aby jste je naučili jak se dělá mobilní aplikace, protože oni o tom nemají ani páru :)

**Comment by vitSkalicky** [comment]
Zatím je jediná forma donatu příspěvek přes Google Play (pouze v Google Play verzi). Možná brzy přibude open collective, ale to nemohu slíbit.
