### ISSUE TITLE
How to exit?

### ISSUE THREAD

**Issue by patrik-cihal** [vitSkalicky/lepsi-rozvrh#7]
Is there a way to exit from the app without having to use force stop in settings?
Maybe a third button in notification area called "exit" would be nice.

**Comment by vitSkalicky** [comment]
What do you mean by 'exiting'? Just leave the app and it will be but into background just like other apps. If you want to hide the permanent notification, disable it in the setting or log out.

**Comment by patrik-cihal** [comment]
No I just don't want it to run in background draining my battery. If I logout I am going to have to login later...

**Comment by vitSkalicky** [comment]
The only thing that drains battery in the background are periodic updates of widgets and permanent notification. Remove all widgets and disable permanent notification to turn them off.

By the way, when the app is in the background, it is not actually running, it is just kept in RAM in case you wanted to open it again soon. When your phone runs out of RAM, the app will be fully terminated and cleared from RAM. Apps do not consume any power when sitting in the RAM. (unless they are poorly programmed)

**Comment by patrik-cihal** [comment]
Ok, but what if I want to hide it from notification area until I reopen the app again? (without permanently changing it in setting)

**Comment by vitSkalicky** [comment]
Well, the app does not have this feature, but it should not display the notification when there are no lessons (for example during holiday or school trips). If it does display it to you anyway, could you send me a screenshot and your current schedule using the 'Send feedback' button in the settings?

**Comment by xVIREx** [comment]
I don't have an issue if that, but still having an exit option would be nice (e.g. when someone doesn't go to school).
